# Generated by Django 2.0.3 on 2018-09-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oneExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('threeExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('special', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='largePrices', to='orders.PriceList')),
                ('small', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallPrices', to='orders.PriceList')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('legalExtras', models.ManyToManyField(to='orders.Extra')),
                ('sizeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SizeList')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='style',
            field=models.ManyToManyField(to='orders.Style'),
        ),
    ]
