# Generated by Django 2.0.3 on 2018-09-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('extras', models.ManyToManyField(blank=True, to='orders.Extra')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ToppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('noTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noTopPrice', to='orders.Price')),
                ('oneTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneTopPrice', to='orders.Price')),
                ('specialTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialTopPrice', to='orders.Price')),
                ('threeTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threeTopPrice', to='orders.Price')),
                ('twoTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twoTopPrice', to='orders.Price')),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ToppingList'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Style'),
        ),
        migrations.AddField(
            model_name='dinnerplate',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price'),
        ),
    ]
