# Generated by Django 2.0.3 on 2018-09-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='style',
        ),
        migrations.AddField(
            model_name='food',
            name='style',
            field=models.ManyToManyField(to='orders.Style'),
        ),
    ]
