# Generated by Django 2.0.3 on 2018-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizelist',
            name='name',
            field=models.CharField(default='Pizza', max_length=32),
            preserve_default=False,
        ),
    ]
