# Generated by Django 2.0.3 on 2018-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sizelist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='legalExtras',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Extra'),
        ),
    ]
