# Generated by Django 2.0.3 on 2018-09-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180917_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
