# Generated by Django 2.0.3 on 2018-09-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180917_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price'),
        ),
    ]
