# Generated by Django 2.0.3 on 2018-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180923_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='legalExtras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
    ]
