# Generated by Django 2.0.3 on 2018-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180920_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='numextra',
            name='parent',
            field=models.CharField(default='1', max_length=32),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='style',
            name='numExtra',
        ),
        migrations.AddField(
            model_name='style',
            name='numExtra',
            field=models.ManyToManyField(to='orders.NumExtra'),
        ),
    ]
