# Generated by Django 2.0.3 on 2018-09-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180920_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallRegular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeRegular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('smallOneExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeOneExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('smallTwoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeTwoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('smallThreeExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeThreeExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('smallSpecial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeSpecial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='numextra',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='style',
            name='numExtra',
        ),
        migrations.DeleteModel(
            name='NumExtra',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='style',
            name='PriceList',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='orders.PriceList'),
            preserve_default=False,
        ),
    ]
