# Generated by Django 2.0.3 on 2018-09-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180917_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlate',
            new_name='DinnerPlatter',
        ),
    ]
