# Generated by Django 2.0.3 on 2018-09-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180920_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='largeRegular',
            new_name='largeNoExtra',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='smallRegular',
            new_name='smallNoExtra',
        ),
    ]
