# Generated by Django 2.0.3 on 2018-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180920_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SandwitchExtra',
            new_name='Extra',
        ),
        migrations.DeleteModel(
            name='PizzaExtra',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='PriceList',
            new_name='priceList',
        ),
        migrations.AddField(
            model_name='style',
            name='legalExtras',
            field=models.ManyToManyField(to='orders.Extra'),
        ),
    ]
