# Generated by Django 2.0.3 on 2018-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180920_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='legalExtras',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Extra'),
        ),
    ]
